exp_dir: exp
exp_name: transformer_wikitext_gpt_gelu
lm:
  batch_size: 64
  context_size: 128
  embed_dim: 256
  epochs: 20
  grad_clip: 1.0
  lr: 0.0003
  num_seeds: 5
  num_workers: 4
model:
  d_ff: 1024
  d_model: 256
  dropout: 0.1
  n_heads: 8
  n_layers: 6
  name: StandardTransformer
run_id: '1232550'
save_dir: exp/transformer_wikitext_gpt_gelu_20260407_022927_7bd0ffb2
seed: 1234
task_type: language_model
use_gpu: true
