exp_dir: exp
exp_name: transformer_wikitext_baseline
lm:
  batch_size: 128
  context_size: 64
  embed_dim: 128
  epochs: 10
  grad_clip: 1.0
  lr: 0.0005
  num_seeds: 5
  num_workers: 4
model:
  d_ff: 512
  d_model: 128
  dropout: 0.1
  n_heads: 4
  n_layers: 4
  name: StandardTransformer
run_id: '21693'
save_dir: exp/transformer_wikitext_baseline_20260303_100822_6c85e187
seed: 1234
task_type: language_model
use_gpu: true
