exp_dir: exp
exp_name: lstm_wikitext_2arg
lm:
  batch_size: 128
  context_size: 32
  embed_dim: 64
  epochs: 10
  grad_clip: 1.0
  hidden_dim: 128
  lr: 0.001
  num_seeds: 5
  num_workers: 4
model:
  inner_hidden: 32
  name: InnerNetLSTMModel
run_id: '663248'
save_dir: exp/lstm_wikitext_2arg_20260302_104043_cd902e6b
seed: 1234
task_type: language_model
use_gpu: true
