dataset:
  data_path: ./data
  loader_name: InnerNetData
  name: ptb
  split: train
exp_dir: ./exp
exp_name: rnn_ptb_2arg
gpus:
- 0
model:
  arg_in_dim: 2
  dropout: 0.5
  embedding_dim: 120
  in_hidden_dim: 64
  inner_net: mlp
  loss: CrossEntropy
  name: ComplexNeuronRNN
  num_cell_types: 10
  out_hidden_dim:
  - 120
pretrain:
  batch_size: 100
  best_model:
  - /model_snapshot_best_pretrained0.pth
  - /model_snapshot_best_pretrained1.pth
  - /model_snapshot_best_pretrained2.pth
  - /model_snapshot_best_pretrained3.pth
  - /model_snapshot_best_pretrained4.pth
  - /model_snapshot_best_pretrained5.pth
  - /model_snapshot_best_pretrained6.pth
  - /model_snapshot_best_pretrained7.pth
  - /model_snapshot_best_pretrained8.pth
  - /model_snapshot_best_pretrained9.pth
  lr: 0.001
  max_epoch: 500
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  shuffle: true
  snapshot_epoch: 1000
  wd: 0.0
run_id: '209123'
save_dir: ./exp/rnn_ptb_2arg_20260305_014454_7bc4ce8c
seed: 1234
test:
  batch_size: 20
  num_workers: 0
  test_model: /model_snapshot_best_phase2.pth
train:
  batch_size: 20
  best_model: /model_snapshot_best_phase1.pth
  bptt: 35
  clip: 0.25
  display_iter: 5000
  early_stop_window: 20
  is_resume: false
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  max_epoch: 30
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_model: None
  shuffle: true
  snapshot_epoch: 1000
  valid_epoch: 1
  wd: 0.0
train_phase2:
  max_epoch: 30
use_gpu: true
