dataset:
  data_path: ./data
  loader_name: InnerNetData
  name: ptb
  split: train
exp_dir: ./exp
exp_name: rnn_ptb_tanh
gpus:
- 0
model:
  dropout: 0.5
  embedding_dim: 120
  loss: CrossEntropy
  name: BaselineRNN
  out_hidden_dim:
  - 130
pretrain:
  batch_size: 100
  best_model: []
  lr: 0.001
  max_epoch: 500
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  shuffle: true
  snapshot_epoch: 1000
  wd: 0.0
run_id: '2355084'
save_dir: ./exp/rnn_ptb_tanh_20260306_080927_b9410ccc
seed: 1234
test:
  batch_size: 20
  num_workers: 0
  test_model: /model_snapshot_best_phase1.pth
train:
  batch_size: 20
  best_model: /model_snapshot_best_phase1.pth
  bptt: 35
  clip: 0.25
  display_iter: 5000
  early_stop_window: 20
  is_resume: false
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  max_epoch: 30
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_model: None
  shuffle: true
  snapshot_epoch: 1000
  valid_epoch: 1
  wd: 0.0
use_gpu: true
