exp_dir: exp
exp_name: dqn_lunarlander_swiglu
model:
  hidden_dim: 256
  name: SwiGLUDQN
rl:
  batch_size: 64
  env_name: LunarLander-v3
  epsilon_decay: 0.995
  epsilon_end: 0.01
  epsilon_start: 1.0
  gamma: 0.99
  log_interval: 50
  lr: 0.001
  memory_size: 10000
  num_episodes: 500
  num_seeds: 10
  target_update: 10
run_id: '982192'
save_dir: exp/dqn_lunarlander_swiglu_20260405_181418_114a41a3
seed: 1234
task_type: rl
use_gpu: true
