dataset:
  data_path: /home/yc/repo/xor_neuron_yoon/data
  loader_name: InnerNetData
  name: mnist
  split: train
exp_dir: /home/yc/repo/xor_neuron_yoon/exp/xor_neuron_mlp_mnist
exp_name: ComplexNeuronMLP_001_mnist_2025-Dec-20-18-51-10
gpus:
- 0
model:
  arg_in_dim: 2
  dropout: 0.5
  in_hidden_dim: 64
  inner_net: mlp
  input_dim: 784
  loss: CrossEntropy
  name: ComplexNeuronMLP
  num_cell_types: 10
  num_classes: 10
  out_hidden_dim:
  - 120
  - 120
  - 120
pretrain:
  batch_size: 100
  best_model:
  - /model_snapshot_best_pretrained1.pth
  - /model_snapshot_best_pretrained2.pth
  - /model_snapshot_best_pretrained3.pth
  - /model_snapshot_best_pretrained4.pth
  - /model_snapshot_best_pretrained5.pth
  - /model_snapshot_best_pretrained6.pth
  - /model_snapshot_best_pretrained7.pth
  - /model_snapshot_best_pretrained8.pth
  - /model_snapshot_best_pretrained9.pth
  - /model_snapshot_best_pretrained10.pth
  lr: 0.001
  max_epoch: 500
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  shuffle: true
  snapshot_epoch: 1000
  wd: 0.0
run_id: '354827'
runner: XorNeuronRunner
save_dir: /home/yc/repo/xor_neuron_yoon/exp/xor_neuron_mlp_mnist/ComplexNeuronMLP_001_mnist_2025-Dec-20-18-51-10
seed: 12345
test:
  batch_size: 100
  num_workers: 0
  test_model: /model_snapshot_best_phase2.pth
train:
  batch_size: 100
  best_model: /model_snapshot_best_phase1.pth
  display_iter: 5000
  is_resume: false
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  max_epoch: 200
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_model: None
  shuffle: true
  snapshot_epoch: 1000
  valid_epoch: 1
  wd: 0.0
use_gpu: true
