# DQN + LunarLander-v3 with InnerNet activation
exp_name: dqn_lunarlander_2arg
task_type: rl
seed: 1234
use_gpu: true
exp_dir: exp

model:
  name: InnerNetDQN
  hidden_dim: 256
  inner_hidden: 32

rl:
  env_name: LunarLander-v3
  num_episodes: 1000
  num_seeds: 10
  gamma: 0.99
  batch_size: 64
  lr: 0.001
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.996
  memory_size: 100000
  target_update: 10
  log_interval: 50
