---
exp_name: xor_neuron_mlp_mnist
exp_dir: /home/yc/repo/xor_neuron_yoon/exp/xor_neuron_mlp_mnist
#exp_dir: ./exp/xor_neuron_mlp_mnist
runner: XorNeuronRunner
use_gpu: true
gpus: [0]
seed: 12345
dataset:
  name: mnist
  loader_name: InnerNetData
  data_path: /home/yc/repo/xor_neuron_yoon/data
#  data_path: ../xor_neuron_data/data
  split: train
model:
  name: ComplexNeuronMLP
  num_cell_types: 10
  inner_net: mlp
  input_dim: 784 #784(mnist)/3072(cifar10)
  arg_in_dim: 2
  in_hidden_dim: 64 #64
  out_hidden_dim: [120,120,120] #[132, 132, 132]
  dropout: 0.5
  num_classes: 10
  loss: CrossEntropy
pretrain:
  optimizer: Adam
  num_workers: 0
  max_epoch: 500 #500
  batch_size: 100
  snapshot_epoch: 1000
  lr: 1.0e-3
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  best_model: [/model_snapshot_best_pretrained1.pth,
               /model_snapshot_best_pretrained2.pth,
               /model_snapshot_best_pretrained3.pth,
               /model_snapshot_best_pretrained4.pth,
               /model_snapshot_best_pretrained5.pth,
               /model_snapshot_best_pretrained6.pth,
               /model_snapshot_best_pretrained7.pth,
               /model_snapshot_best_pretrained8.pth,
               /model_snapshot_best_pretrained9.pth,
               /model_snapshot_best_pretrained0.pth]
train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_steps: [10000]
  num_workers: 0
  max_epoch: 200
  batch_size: 100
  display_iter: 5000
  snapshot_epoch: 1000
  valid_epoch: 1
  lr: 1.0e-3
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_model: None
  best_model: /model_snapshot_best_phase1.pth
test:
  batch_size: 100
  num_workers: 0
  test_model: /model_snapshot_best_phase2.pth
