exp_dir: exp
exp_name: dqn_cartpole_2arg
model:
  inner_hidden: 32
  name: InnerNetDQN
rl:
  batch_size: 64
  env_name: CartPole-v1
  epsilon_decay: 0.995
  epsilon_end: 0.01
  epsilon_start: 1.0
  gamma: 0.99
  log_interval: 50
  lr: 0.001
  memory_size: 10000
  num_episodes: 500
  num_seeds: 10
  target_update: 10
run_id: '524931'
save_dir: exp/dqn_cartpole_2arg_20260301_204801_4ab7bd36
seed: 1234
task_type: rl
use_gpu: true
