dataset:
  data_path: ./data
  loader_name: InnerNetData
  name: mnist
  split: train
exp_dir: ./exp
exp_name: cnn_mnist_1arg
gpus:
- 0
model:
  arg_in_dim: 1
  dropout: 0.5
  in_channel: 64
  inner_net: conv
  input_channel: 1
  kernel_size:
  - 3
  - 3
  - 3
  - 1
  loss: CrossEntropy
  name: XorNeuronConv
  num_cell_types: 1
  num_classes: 10
  out_channel:
  - 60
  - 120
  - 120
  - 120
  stride:
  - 1
  - 1
  - 1
  - 1
  zero_pad:
  - 0
  - 0
  - 0
  - 0
pretrain:
  batch_size: 100
  best_model:
  - /model_snapshot_best_pretrained0.pth
  lr: 0.001
  max_epoch: 500
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  shuffle: true
  snapshot_epoch: 1000
  wd: 0.0
run_id: '634279'
save_dir: ./exp/cnn_mnist_1arg_20260305_085309_5b2c1273
seed: 1234
test:
  batch_size: 100
  num_workers: 0
  test_model: /model_snapshot_best_phase2.pth
train:
  batch_size: 100
  best_model: /model_snapshot_best_phase1.pth
  display_iter: 5000
  early_stop_window: 20
  is_resume: false
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  max_epoch: 200
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_model: None
  shuffle: true
  snapshot_epoch: 1000
  valid_epoch: 1
  wd: 0.0
train_phase2:
  max_epoch: 400
use_gpu: true
